CREATE TABLE ag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wochentag VARCHAR(20),
    zeit VARCHAR(20),
    kategorie VARCHAR(30),
    titel VARCHAR(255) NOT NULL UNIQUE,
    beschreibung TEXT,
    verantwortlicher VARCHAR(255),
    ort VARCHAR(255),
    maximale_teilnehmerzahl INTEGER
);

CREATE TABLE erlaubter_jahrgang (
    ag_id INTEGER NOT NULL,
    position INTEGER NOT NULL,
    jahrgang INTEGER NOT NULL,
    PRIMARY KEY (ag_id, position)
);

CREATE TABLE teilnehmer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    klasse VARCHAR(2) NOT NULL,
    gt_teilnahme VARCHAR(5) NOT NULL DEFAULT 'JA',
    UNIQUE (vorname, name)
);

CREATE TABLE einwahl_entdeckerangebot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id INTEGER NOT NULL,
    ag_titel VARCHAR(255) NOT NULL,
    auswahl VARCHAR(10),
    zugewiesen BOOLEAN,
    UNIQUE (teilnehmer_id, ag_titel)
);

CREATE TABLE einwahl_ag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id INTEGER NOT NULL,
    ag_titel VARCHAR(255) NOT NULL,
    auswahl INTEGER,
    zugewiesen BOOLEAN,
    UNIQUE (teilnehmer_id, ag_titel)
);

CREATE TABLE einwahl_vormittags_ag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id INTEGER NOT NULL,
    ag_titel VARCHAR(255) NOT NULL,
    auswahl VARCHAR(10),
    zugewiesen BOOLEAN,
    UNIQUE (teilnehmer_id, ag_titel)
);
