CREATE TABLE ag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wochentag VARCHAR(20),
    zeit VARCHAR(20),
    kategorie VARCHAR(30),
    titel VARCHAR(255) NOT NULL UNIQUE,
    verantwortlicher VARCHAR(255),
    ort VARCHAR(255),
    maximale_teilnehmerzahl INTEGER
);

CREATE TABLE teilnehmer (
    nr INTEGER PRIMARY KEY,
    vorname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    klasse VARCHAR(2) NOT NULL,
    UNIQUE (vorname, name)
);

CREATE TABLE einwahl_entdeckerangebot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_nr INTEGER NOT NULL,
    teilnehmer_vorname VARCHAR(255) NOT NULL,
    teilnehmer_name VARCHAR(255) NOT NULL,
    teilnehmer_klasse VARCHAR(2) NOT NULL,
    ag_id INTEGER,
    ag_wochentag VARCHAR(20),
    ag_zeit VARCHAR(20),
    ag_kategorie VARCHAR(30),
    ag_titel VARCHAR(255) NOT NULL,
    ag_verantwortlicher VARCHAR(255),
    ag_ort VARCHAR(255),
    ag_maximale_teilnehmerzahl INTEGER,
    auswahl VARCHAR(10),
    UNIQUE (teilnehmer_nr, ag_titel)
);

CREATE TABLE einwahl_ag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_nr INTEGER NOT NULL,
    teilnehmer_vorname VARCHAR(255) NOT NULL,
    teilnehmer_name VARCHAR(255) NOT NULL,
    teilnehmer_klasse VARCHAR(2) NOT NULL,
    ag_id INTEGER,
    ag_wochentag VARCHAR(20),
    ag_zeit VARCHAR(20),
    ag_kategorie VARCHAR(30),
    ag_titel VARCHAR(255) NOT NULL,
    ag_verantwortlicher VARCHAR(255),
    ag_ort VARCHAR(255),
    ag_maximale_teilnehmerzahl INTEGER,
    auswahl INTEGER,
    UNIQUE (teilnehmer_nr, ag_titel)
);

CREATE TABLE einwahl_vormittags_ag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_nr INTEGER NOT NULL,
    teilnehmer_vorname VARCHAR(255) NOT NULL,
    teilnehmer_name VARCHAR(255) NOT NULL,
    teilnehmer_klasse VARCHAR(2) NOT NULL,
    ag_id INTEGER,
    ag_wochentag VARCHAR(20),
    ag_zeit VARCHAR(20),
    ag_kategorie VARCHAR(30),
    ag_titel VARCHAR(255) NOT NULL,
    ag_verantwortlicher VARCHAR(255),
    ag_ort VARCHAR(255),
    ag_maximale_teilnehmerzahl INTEGER,
    auswahl INTEGER,
    UNIQUE (teilnehmer_nr, ag_titel)
);
